-- ============================================================
-- 01 — Snowflake Warehouse and Database Setup
-- Run once as ACCOUNTADMIN or SYSADMIN
-- ============================================================

USE ROLE SYSADMIN;

-- ── Virtual Warehouse ──────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS ZIM_PROPERTY_WH
    WITH
    WAREHOUSE_SIZE        = 'X-SMALL'
    AUTO_SUSPEND          = 120          -- suspend after 2 min idle
    AUTO_RESUME           = TRUE
    INITIALLY_SUSPENDED   = TRUE
    COMMENT               = 'Zimbabwe Property Platform — main compute';

-- ── Database ───────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS ZIM_PROPERTY_DB
    COMMENT = 'Zimbabwe Real Estate Market Intelligence';

-- ── Schemas ────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS ZIM_PROPERTY_DB.RAW
    COMMENT = 'Raw scraped data — never modified after load';

CREATE SCHEMA IF NOT EXISTS ZIM_PROPERTY_DB.STAGING
    COMMENT = 'Cleaned and standardised listings (dbt staging)';

CREATE SCHEMA IF NOT EXISTS ZIM_PROPERTY_DB.INTERMEDIATE
    COMMENT = 'Intermediate models — enriched data (dbt intermediate)';

CREATE SCHEMA IF NOT EXISTS ZIM_PROPERTY_DB.ANALYTICS
    COMMENT = 'Final analytics marts for BI and dashboards';

CREATE SCHEMA IF NOT EXISTS ZIM_PROPERTY_DB.DATA_QUALITY
    COMMENT = 'Data quality audit tables';

-- ── Roles ──────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS ZIM_SCRAPER_ROLE
    COMMENT = 'Used by the Scrapy pipeline to write raw data';

CREATE ROLE IF NOT EXISTS ZIM_DBT_ROLE
    COMMENT = 'Used by dbt to read raw and write transformed layers';

CREATE ROLE IF NOT EXISTS ZIM_ANALYST_ROLE
    COMMENT = 'Read-only access to analytics schema';

-- ── Grants ─────────────────────────────────────────────────
GRANT USAGE ON WAREHOUSE ZIM_PROPERTY_WH TO ROLE ZIM_SCRAPER_ROLE;
GRANT USAGE ON WAREHOUSE ZIM_PROPERTY_WH TO ROLE ZIM_DBT_ROLE;
GRANT USAGE ON WAREHOUSE ZIM_PROPERTY_WH TO ROLE ZIM_ANALYST_ROLE;

GRANT USAGE ON DATABASE ZIM_PROPERTY_DB TO ROLE ZIM_SCRAPER_ROLE;
GRANT USAGE ON DATABASE ZIM_PROPERTY_DB TO ROLE ZIM_DBT_ROLE;
GRANT USAGE ON DATABASE ZIM_PROPERTY_DB TO ROLE ZIM_ANALYST_ROLE;

-- Scraper: full access to RAW schema only
GRANT USAGE  ON SCHEMA ZIM_PROPERTY_DB.RAW TO ROLE ZIM_SCRAPER_ROLE;
GRANT INSERT, UPDATE, SELECT ON ALL TABLES IN SCHEMA ZIM_PROPERTY_DB.RAW TO ROLE ZIM_SCRAPER_ROLE;
GRANT INSERT, UPDATE, SELECT ON FUTURE TABLES IN SCHEMA ZIM_PROPERTY_DB.RAW TO ROLE ZIM_SCRAPER_ROLE;

-- dbt: read raw, write staging/intermediate/analytics
GRANT USAGE  ON SCHEMA ZIM_PROPERTY_DB.RAW TO ROLE ZIM_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ZIM_PROPERTY_DB.RAW TO ROLE ZIM_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ZIM_PROPERTY_DB.RAW TO ROLE ZIM_DBT_ROLE;

GRANT ALL ON SCHEMA ZIM_PROPERTY_DB.STAGING      TO ROLE ZIM_DBT_ROLE;
GRANT ALL ON SCHEMA ZIM_PROPERTY_DB.INTERMEDIATE TO ROLE ZIM_DBT_ROLE;
GRANT ALL ON SCHEMA ZIM_PROPERTY_DB.ANALYTICS    TO ROLE ZIM_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA ZIM_PROPERTY_DB.STAGING      TO ROLE ZIM_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA ZIM_PROPERTY_DB.INTERMEDIATE TO ROLE ZIM_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA ZIM_PROPERTY_DB.ANALYTICS    TO ROLE ZIM_DBT_ROLE;

-- Analyst: read analytics only
GRANT USAGE  ON SCHEMA ZIM_PROPERTY_DB.ANALYTICS TO ROLE ZIM_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA ZIM_PROPERTY_DB.ANALYTICS TO ROLE ZIM_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA ZIM_PROPERTY_DB.ANALYTICS TO ROLE ZIM_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ZIM_PROPERTY_DB.ANALYTICS TO ROLE ZIM_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ZIM_PROPERTY_DB.ANALYTICS TO ROLE ZIM_ANALYST_ROLE;

-- ── Users (placeholders — replace with actual credentials) ─
-- CREATE USER scraper_svc PASSWORD = '...' DEFAULT_ROLE = ZIM_SCRAPER_ROLE;
-- CREATE USER dbt_svc     PASSWORD = '...' DEFAULT_ROLE = ZIM_DBT_ROLE;
-- GRANT ROLE ZIM_SCRAPER_ROLE TO USER scraper_svc;
-- GRANT ROLE ZIM_DBT_ROLE     TO USER dbt_svc;
